### ISSUE TITLE
feature-request: add typings for typescript support

### ISSUE THREAD

**Issue by mattmeye** [chartmogul/chartmogul-node#28]
see http://definitelytyped.org/

**Comment by pkopac** [comment]
Hi @mattmeye! Thank you for the suggestion. We haven't planned that previously and since this is not a bug report, I can't promise when/if it will be done. We would gladly accept a PR, though, if you happen to have done it for your needs already.

**Comment by hassansin** [comment]
@mattmeye you can now find the defintions at https://www.npmjs.com/package/@types/chartmogul-node. Please let us know if you face any issue using it.

**Comment by okhomenko** [comment]
@types/chartmogul-node are outdated. Miss-match right of the bat `@types/chartmogul-node`
```ts
export class Config {
    VERSION: string;
    API_BASE: string;
    retries: number;

    constructor(token: string, secret: string, base?: string);
    getAccountToken(): string;
    getSecretKey(): string;
}
```

vs `chartmogul-node`
```ts
class Config {
  constructor (apiKey, apiBase) {
    this.apiKey = apiKey;
    this.apiBase = apiBase || API_BASE;
  }
```

```
[Nest] 87015  - 03/12/2022, 6:08:58 AM   ERROR [ExceptionsHandler] Invalid URI "abcd12312312312312apikey/v1/ping"
Error: Invalid URI "abcd12312312312312apikey/v1/ping"
    at Request.init (/Users/okhomenko/chartmogul-integration/node_modules/request/request.js:273:31)
    at new Request (/Users/okhomenko/chartmogul-integration/node_modules/request/request.js:127:8)
    at request (/Users/okhomenko/chartmogul-integration/node_modules/request/index.js:53:10)
    at RetryOperation._fn (/Users/okhomenko/chartmogul-integration/node_modules/chartmogul-node/lib/chartmogul/util/retry.js:46:5)
    at RetryOperation.attempt (/Users/okhomenko/chartmogul-integration/node_modules/retry/lib/retry_operation.js:112:8)
    at Object.retryRequest (/Users/okhomenko/chartmogul-integration/node_modules/chartmogul-node/lib/chartmogul/util/retry.js:45:13)
    at /Users/okhomenko/chartmogul-integration/node_modules/chartmogul-node/lib/chartmogul/resource.js:68:12
    at new Promise (<anonymous>)
    at Function.request (/Users/okhomenko/chartmogul-integration/node_modules/chartmogul-node/lib/chartmogul/resource.js:40:21)
    at Function.ping (/Users/okhomenko/chartmogul-integration/node_modules/chartmogul-node/lib/chartmogul/resource.js:145:19)
```
