### ISSUE TITLE
Importing invoice fails

### ISSUE THREAD

**Issue by alexblack** [chartmogul/chartmogul-node#8]
If I attempt to import this invoice using the library, it fails, but, using curl it works fine.

code:

```
        canceled_at = sub.autorenewing == false ? sub.expiry_dt : null;

        lineItems = [{
          type: 'subscription',
          subscription_external_id: sub.order_id,
          plan_uuid: planMap[sub.order_sku],
          service_period_start: sub.order_dt.toString(),
          due_date: sub.order_dt.toString(),
          service_period_end: sub.expiry_dt ? sub.expiry_dt.toString() : null,
          //cancelled_at: canceled_at ? canceled_at.toString() : null,
          amount_in_cents: sub.amount_in_cents
        }];
        data = {
          external_id: sub.id,
          date: sub.order_dt ? sub.order_dt.toString() : null,
          currency: sub.currency_code,
          line_items: lineItems
        };
        console.log(data)
        ChartMogul.Import.Invoice.create(config, cust.uuid, data, (err, res) => {
          if (err)
            defer.reject(err);
          else
            defer.resolve(res);
        });
```
Console log of `data`:

```
{ external_id: 'Zr6AlcCIRQ6xR4gyZzeTFA',
  date: 'Sun Jul 26 2015 03:38:55 GMT-0700 (PDT)',
  currency: 'CAD',
  line_items:
   [ { type: 'subscription',
       subscription_external_id: 'GPA.1343-7803-4956-35795',
       plan_uuid: 'pl_196e2566-2346-4263-9599-f9e164e0f308',
       service_period_start: 'Sun Jul 26 2015 03:38:55 GMT-0700 (PDT)',
       due_date: 'Sun Jul 26 2015 03:38:55 GMT-0700 (PDT)',
       service_period_end: 'Mon Sep 12 2016 22:59:40 GMT-0700 (PDT)',
       amount_in_cents: 349 } ] }
```

Error:

```
{ SchemaInvalidError: JSON schema validation hasn't passed.
    at new SchemaInvalidError (/Users/alex/dev/is/web/node_modules/chartmogul-node/lib/chartmogul/errors/schema-invalid-error.js:7:11)
    at Request.request [as _callback] (/Users/alex/dev/is/web/node_modules/chartmogul-node/lib/chartmogul/resource.js:80:19)
    at Request.self.callback (/Users/alex/dev/is/web/node_modules/chartmogul-node/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/alex/dev/is/web/node_modules/chartmogul-node/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/alex/dev/is/web/node_modules/chartmogul-node/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'SchemaInvalidError',
  response: { error: 'The property \'#/\' did not contain a required property of \'invoices\'' },
  httpStatus: 400 }
```

curl:

```
curl -i -X POST "https://api.chartmogul.com/v1/import/customers/cus_3e8226d6-d613-407b-a0bb-fd6e504eff97/invoices" \
     -u TOKEN:SECRET \
     -H "Content-Type: application/json" \
     -d '{
     "invoices":[
{ "external_id": "Zr6AlcCIRQ6xR4gyZzeTFA",
  "date": "Sun Jul 26 2015 03:38:55 GMT-0700 (PDT)",
  "currency": "CAD",
  "line_items":
   [ { "type": "subscription",
       "subscription_external_id": "GPA.1343-7803-4956-35795",
       "plan_uuid": "pl_196e2566-2346-4263-9599-f9e164e0f308",
       "service_period_start": "Sun Jul 26 2015 03:38:55 GMT-0700 (PDT)",
       "due_date": "Sun Jul 26 2015 03:38:55 GMT-0700 (PDT)",
       "service_period_end": "Mon Sep 12 2016 22:59:40 GMT-0700 (PDT)",
       "amount_in_cents": 349 } ] }
        ]
     }'

HTTP/1.1 201 Created
Server: nginx/1.9.10
Date: Sun, 14 Aug 2016 03:23:57 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
ETag: W/"2f29292d7b287d93de52197e33d4e2ab"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: eaf45e86-d9c7-48f5-a25e-94a38d3d9ae5
X-Runtime: 0.125522
Strict-Transport-Security: max-age=15768000

{"invoices":[{"uuid":"inv_99492f7f-f29d-4419-978d-3daedde77a11","external_id":"Zr6AlcCIRQ6xR4gyZzeTFA","date":"2015-07-26T10:38:55.000Z","due_date":null,"currency":"CAD","line_items":[{"uuid":"li_caa3a567-da86-46cc-a6f8-d5e044283aff","external_id":null,"type":"subscription","subscription_uuid":"sub_2f6f9937-6114-49f5-8190-6e8ee4b666cd","plan_uuid":"pl_196e2566-2346-4263-9599-f9e164e0f308","prorated":false,"service_period_start":"2015-07-26T10:38:55.000Z","service_period_end":"2016-09-13T05:59:40.000Z","amount_in_cents":349,"quantity":1,"discount_code":"","discount_amount_in_cents":0,"tax_amount_in_cents":0}],"transactions":[]}]}Alexs-MacBook-Pro:web alex$

```

**Comment by alexblack** [comment]
Got it figured, failed to wrap the json in `invoices: []`
